#!/bin/sh
#
# oauth2_proxy - this script starts and stops the oauth2_proxy daemon
#
# chkconfig:   - 85 15
# description:  Nginx is an HTTP(S) server, HTTP(S) reverse \
#               proxy and IMAP/POP3 proxy server
# processname: oauth2_proxy
# config:      /etc/oauth2_proxy/oauth2_proxy.conf


# Source function library.
. /etc/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

APP_PATH=/var/www/go/oauth2_proxy
EXEC=oauth2_proxy
DAEMON=$APP_PATH/$EXEC

LOGFILE=$APP_PATH/oauth2_proxy.log

if [ -f /etc/sysconfig/oauth2_proxy ];then
        . /etc/sysconfig/oauth2_proxy
fi

prog='Oauth2 Proxy Service'

start() {
	# Check that networking is up.
	[ "$NETWORKING" = "no" ] && exit 1
	
        echo -n $"Starting $prog: "
	daemon $DAEMON $OPTIONS < /dev/null > $LOGFILE &
	RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$EXEC
	return $RETVAL
}
	
stop() {
        echo -n $"Shutting down $prog: "
	killproc $EXEC
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$EXEC
	return $RETVAL
}

# See how we were called.
case "$1" in
  start)
	start
        ;;
  stop)
	stop
        ;;
  status)
	status $EXEC
	RETVAL=$?
	;;
  restart|reload)
	stop
	start
	RETVAL=$?
	;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        RETVAL=3
esac

exit $RETVAL
