#!/bin/sh
track_id=$1
oauth_token=$2
client_id="02gUJC0hH2ct1EGOcYXQIzRFU91c72Ea"
requesturl=`echo "http://api.soundcloud.com/i1/tracks/$track_id/streams?oauth_token=$oauth_token&client_id=$client_id"`
json=`wget -qO- $requesturl`
prop='http_mp3_128_url'
streamurl=`echo $json | sed 's/[{}]//g' | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | sed 's/\"\:\"/\|/g' | sed 's/[\,]/ /g' | sed 's/\"//g' | grep -w $prop`
streamurl=`echo ${streamurl##*|} | sed -e 's/ u0026/\&/g' | sed -e 's/https/http/g'`
wget -qO- $streamurl | madplay - -v --tty-control